db.restaurants.find( {} );
db.restaurants.find( {}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 });
db.restaurants.find( {}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0 });
db.restaurants.find( {}, { restaurant_id: 1, name: 1, borough: 1, "address.zipcode": 1, _id: 0 });
db.restaurants.find( {borough: 'Bronx'})
db.restaurants.find( {borough: 'Bronx'}).limit(5)
db.restaurants.find( {borough: 'Bronx'}).skip(5).limit(5)
db.restaurants.find({ grades: { $elemMatch: {"score" :{ $gt: 90} }}})
db.restaurants.find({ grades: { $elemMatch: {"score" :{ $gt: 80, $lt : 100}}}})
db.restaurants.find({"address.coord.0": {$lt: -95.754168} })
db.restaurants.find({ grades: { $elemMatch: {"score" :{ $gt: 70}}}, "address.coord.0": {$lt: -65.754168}, cuisine: {$ne: 'American '}})
db.restaurants.find({ grades: { $elemMatch: {"score" :{ $gt: 70}}}, "address.coord.0": {$lt: -65.754168}, cuisine: {$ne: 'American '}})
db.restaurants.find({ grades: { $elemMatch: {grade :'A'}}, "address.coord.0": {$lt: -65.754168}, cuisine: {$ne: 'American '}, borough:{$ne: 'Brooklyn'}}).sort({ cuisine: -1 })
db.restaurants.find({ name: /^Wil/}, {restaurant_id:true, name:true, borough:true, cuisine:true, _id:0})
db.restaurants.find({ name: /ces$/}, {restaurant_id:true, name:true, borough:true, cuisine:true, _id:0})
db.restaurants.find({ name: /Reg/}, {restaurant_id:true, name:true, borough:true, cuisine:true, _id:0})
db.restaurants.find({borough: 'Bronx', $or: [ { cuisine: 'American '}, { cuisine: 'Chinese'}]})
db.restaurants.find({ $or: [ { borough: 'Staten Island'}, { borough: 'Queens'}, { borough: 'Bronx'}, { borough: 'Brooklyn'} ]}, {restaurant_id:true, name:true, borough:true, cuisine:true, _id:0})
db.restaurants.find({ $and: [ { borough: {$ne: 'Staten Island'}}, { borough: {$ne: 'Queens'}}, { borough: {$ne: 'Bronx'}}, { borough: {$ne: 'Brooklyn'}} ]}, {restaurant_id:true, name:true, borough:true, cuisine:true, _id:0})
db.restaurants.find({ grades: { $elemMatch: {"score" :{ $lte: 90} }}},{restaurant_id:true, name:true, borough:true, cuisine:true, _id:0})
db.restaurants.find({ $and: [ {cuisine:"Seafood"}, { cuisine: {$ne: 'American '}}, { cuisine: {$ne: 'Chinese'}}, { name: {$ne: '/^Wil/'}} ]},{restaurant_id:true, name:true, borough:true, cuisine:true, _id:0})
db.restaurants.find({"grades.grade": 'A', 'grades.score': 11, "grades.date":ISODate("2014-08-11T00:00:00Z")}, {restaurant_id:true, name:true, grades:true, _id:0})
db.restaurants.find({"grades.1.grade": 'A', 'grades.1.score': 9, "grades.1.date":ISODate("2014-08-11T00:00:00Z")}, {restaurant_id:true, name:true, grades:true, _id:0})
db.restaurants.find({"address.coord.1": {$gt: 42, $lt: 52} }, {restaurant_id:true, name:true, address:true, coord:true, _id:0})
db.restaurants.find({}).sort({name:1})
db.restaurants.find({}).sort({name:-1})
db.restaurants.find({}).sort({name:1,borough:-1 })
db.restaurants.find( { "address.street": { $exists: true } } )
db.restaurants.find({"address.coord":{$type: 1}})
db.restaurants.find( { "grades.score": {$mod:[7,0]}}, {restaurant_id:true, name:true, grades: true, _id:0})
db.restaurants.find({ name: /mon/}, {name:true, borough:true, "address.coord":true, cuisine:true, _id:0})
db.restaurants.find({ name: /^Mad/}, {name:true, borough:true, "address.coord":true, cuisine:true, _id:0})